job('First-Maven-Project-Via-DSL') {
	description("First maven project generated by the DSL on ${new Date()}, the project is small maven project")
	scm {
		git {
			remote {
				name('origin')
				url('https://github.com/mszymczak94/advent-of-code-2020.git')
			}
		branch('master')
		}
	}
	triggers {
		scm('* * * * *')
	}
	steps {
		maven('clean package', 'pom.xml')
	}
	publishers {
		archiveArtifacts('**/*.jar')
	}
}